version: '3.5'

services:

  namesrv:
    container_name: rocketmq-namesrv
    image: apache/rocketmq:latest
    environment:
      JAVA_OPT_EXT: -server -Xms256m -Xmx256m -Xmn256m
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-./volumes}/logs:/home/rocketmq/logs
    ports:
      - "127.0.0.1:9876:9876"
    command: sh ./mqnamesrv

  broker:
    container_name: rocketmq-broker
    image: apache/rocketmq:latest
    environment:
      NAMESRV_ADDR: namesrv:9876
      JAVA_OPT_EXT: -server -Xms512m -Xmx512m -Xmn256m
      BROKER_CONF: |
        brokerClusterName = MinimalCluster
        brokerName = broker-a
        brokerId = 0
        deleteWhen = 04
        fileReservedTime = 48
        brokerRole = ASYNC_MASTER
        flushDiskType = ASYNC_FLUSH
        brokerIP1=localhost
    volumes:
      - ${DOCKER_VOLUME_DIRECTORY:-./volumes}/logs:/home/rocketmq/logs
      - ${DOCKER_VOLUME_DIRECTORY:-./volumes}/store:/home/rocketmq/store
    ports:
      # Dashboard pass through
      - "127.0.0.1:8080:8080" 
      - "127.0.0.1:10909:10909"
      - "127.0.0.1:10911:10911"
      - "127.0.0.1:10912:10912"
    command: |
      bash -c '
      mkdir -p /home/rocketmq/conf && 
      echo "$$BROKER_CONF" > /home/rocketmq/conf/broker.conf && 
      ./mqbroker -c /home/rocketmq/conf/broker.conf
      '

  dashboard:
    container_name: rocketmq-dashboard
    image: apacherocketmq/rocketmq-dashboard:latest
    # Access broker with localhost, port 8080 exposed in broker service
    network_mode: "service:broker"
    environment:
      JAVA_OPTS: -Drocketmq.namesrv.addr=namesrv:9876

networks:
  default:
    name: rocketmq-network
